### ISSUE TITLE
[BUG] Transition often jumps to next card instead of smoothly animating

### ISSUE THREAD

**Issue by chrysb** [fermoya/SwiftUIPager#193]
**Describe the bug**
When swiping through pages quickly, I notice that sometimes it animates smoothly and other times it seems to not animate and just jump to the next card

Video:

https://user-images.githubusercontent.com/120388/109396137-f8fae180-78e4-11eb-8f80-fe286d3ad2d9.mp4

**Environment:**
 - iOS
 - iPhone 12 XS Max
- 2.0.2

**Additional context**
I tried it on the simulator and on the device, with example projects and I'm able to reproduce the issue consistently.

**Comment by chrysb** [comment]
I installed some older versions and it seems like the issue was introduced in `2.0.1`

**Comment by fermoya** [comment]
Hi @chrysb thanks a lot for your the feedback. I'll give it a look ASAP. In the meantime please use `2.0.0`.

The video shows a manual transition. Is this the scenario where you detected the bug. I'm basically asking if your sample code used a manual transition (hit a button to go to next page) or it was some scenario where the user dragged the elements

**Comment by fermoya** [comment]
@chrysb what are you doing exactly? I'm on `develop` and the example seems fine. This is `iPhone 12 Pro Max`.
https://user-images.githubusercontent.com/11335612/109400073-7868cf00-793e-11eb-85e3-c5441059882b.mov

**Comment by vanities** [comment]
I've been experiencing this on `14.4` and `14.5` (beta) when swiping too fast sometimes on `tags/2.0.2` and `iPhone 12 Pro Max`. It also seems that `onPageChanged` isn't being called either in these instances.

**Comment by fermoya** [comment]
I've created a new branch where I'm dealing with some minor issues. I pushed some changes in case you guys wanna gimme some feedback @vanities @chrysb . The branch is called `fix/ios13-issues`.

I'll see if I can give it a bit more testing before making a beta release

**Comment by fermoya** [comment]
[`2.1.0`](https://github.com/fermoya/SwiftUIPager/releases/tag/2.1.0)

**Comment by vanities** [comment]
Sorry, I just saw this! I will test right now!

**Comment by beeirl** [comment]
hey @fermoya. I have just updated to `2.1.0` but it seems like this issue still occurs on my end.
Tested this on my `iPhone 12 Pro` `14.4.2`.
Am I missing something?

https://user-images.githubusercontent.com/9655723/113012993-9747c480-917b-11eb-857c-954cc86d69d0.MP4

**Comment by fermoyadrop** [comment]
Hi @beeirl are you testing on a simulator or real device?

**Comment by beeirl** [comment]
@fermoyadrop on a real device

**Comment by chrysb** [comment]
I can confirm this is still happening. Thanks for working on this! SwiftUIPager will be powering a core interaction in our new app.

**Comment by fermoya** [comment]
Hi @chrysb , I’ve left a WIP in #207  if you want to take a look

**Comment by chrysb** [comment]
> Hi @chrysb , I’ve left a WIP in #207 if you want to take a look

Would love to, but can't seem to load the `dragging-animation` branch via SPM. Sorry for the dumb question, but do you know how?

**Comment by chrysb** [comment]
@fermoya I tried it out and still experienced the issue, although it feels less pronounced. I also noticed a drop in FPS.

FYI — I'm using an `interactiveSpring` animation.

**Comment by fermoya** [comment]
Hi @chrysb , what do you mean by FPS? `interactiveSpring` is a faster animation than `.default`, is that what you mean?

Also, can you send a video? I've been trying `.draggingAnimation(.custom(,interactiveSpring))` and it seems fine. I don't think using a spring there is the right choice, at least one with a big response.

**Comment by chrysb** [comment]
@fermoya By FPS I mean the actual framerate, it appears "laggy" as it seems to be dropping frames (a performance issue) that goes away when I revert back to `2.1.0`.

Unfortunately I can't take a video because it's an unreleased product, wish I could be more helpful there.

Also, I was wrong, my animation is an `.interpolatingSpring`

**Comment by fermoya** [comment]
@chrysb I see. There's some stuff to have in mind here. There's two animations in place:
- `onDragChanged`
- `onDragEnded`

Version `2.0.0` has both as `.default` and lets you changed `onDragEnded` animation. Version `2.1.0` changed `onDragChanged` animation from `.default` to `.linear(duration: 0.1)`. This was fit to the fact `.default` animation made the animation delay while dragging (see #157). However, when the drag is fast enough, the last animations (`onDragEnded` seems ignored by SwiftUI) and that's why I suggested using the same animation on both `onDragChanged` and `onDragEnded`. This solution that you just tried doesn't work well with springs if the response is too high. I don't thing `interpolatingSpring` would work well. `interactiveSpring` would work better but it might still be too long of an animation. I'm thinking of enabling different animations for both events and let the user decide of what's best for them because I'm out of ideas here 🤷‍♂️

**Comment by chrysb** [comment]
@fermoya Thanks this is helpful to know! Did you build this using SwiftUI's `DragGesture` or is it UIKit under the hood?

**Comment by fermoya** [comment]
@chrysb this is a `DragGesture` from SwiftUI. If you take a look to the documentation,they're very specific about springs. See `interactiveSpring` [here](https://developer.apple.com/documentation/swiftui/animation/interactivespring(response:dampingfraction:blendduration:)):
> A convenience for a spring() animation with a lower response value, intended for driving interactive animations.

**Comment by chrysb** [comment]
> @chrysb this is a `DragGesture` from SwiftUI. If you take a look at the documentation,they're very specific about springs. See `interactiveSpring` [here](https://developer.apple.com/documentation/swiftui/animation/interactivespring(response:dampingfraction:blendduration:)):
> 
> > A convenience for a spring() animation with a lower response value, intended for driving interactive animations.

Interesting! I'll give that a shot and see. Thank you :)
