### ISSUE TITLE
SwiftUIPager gets stuck upon Touch cancellation

### ISSUE THREAD

**Issue by cocos2dbeginner** [fermoya/SwiftUIPager#69]
Hi Fernando,

really appreciate your work. Awesome repository. I found an issue which should be easy fixable I think.

### Issue
The page freezes in its position when the touch is cancelled.

Steps to reproduce:
1. Open the example project
2. Open any pager
3. Swipe a page just half way and hold it
4. Use your other finger to drag down the control center or notification center (it can also be something else which cancels the touch for the pager)
5. Release all your fingers
6. Go back to the app

### Result
The pager is stuck halfway.

### Expected Result
The pager should snap back to a page (either the selected, or - if the travel was enough- to the next/previous one).

### Gif showing the issue

![ezgif com-video-to-gif (1)](https://user-images.githubusercontent.com/520159/86509029-2a1e2300-bde5-11ea-9870-3503690d8378.gif)

Probably need to listen to a some touch cancelled event?

BR

**Comment by fermoya** [comment]
Hi @cocos2dbeginner, thanks for raising this. I've found a [similar issue](https://stackoverflow.com/questions/60253490/swiftui-detect-draggesture-cancellation-when-ipad-dock-is-pulled-up) in SO, it seems the state didn't reset because the gesture got interrupted.

I'll be making a change within the next days to use `updating(state)` rather than `onChanged` and `onEnded`, I'll keep you posted.

**Comment by fermoya** [comment]
@cocos2dbeginner , I just released [v1.8.0-beta.2](https://github.com/fermoya/SwiftUIPager/releases/tag/1.8.0-beta.2) with a fix to reset the dragging state if the App resigns active (it's interrupted in this case). 

Could you please confirm this solves the issue?

**Comment by cocos2dbeginner** [comment]
@fermoya thanks for the fast update!
I just tested in with the provided example project and something seems a bit off.
The pager gets reset when I pull down the _notification center_ as it is supposed to be. But when I drag down the _control center_ the pager still gets stuck sometimes and does not reset.
I attached a gif showcasing the problem.
 
![ezgif com-video-to-gif (2)](https://user-images.githubusercontent.com/520159/86615089-47551c00-bfb4-11ea-9d0c-9a380c14b0d2.gif)

**Comment by fermoya** [comment]
@cocos2dbeginner could you debug `Pager` and tell me if `onDragGestureEnded` and `onReceive` get called when it gets stuck, please?

**Comment by cocos2dbeginner** [comment]
@fermoya I debugged it and it is being called. But the pager is still stuck.

![Bildschirmfoto 2020-07-07 um 19 01 26](https://user-images.githubusercontent.com/520159/86816669-658a4d00-c084-11ea-9760-513ced84379b.png)
![Bildschirmfoto 2020-07-07 um 19 01 15](https://user-images.githubusercontent.com/520159/86816675-67541080-c084-11ea-8cd5-c6b08caca711.png)
![Bildschirmfoto 2020-07-07 um 19 00 50](https://user-images.githubusercontent.com/520159/86816678-67541080-c084-11ea-864a-e672f6fcd22d.png)

**Comment by fermoya** [comment]
@cocos2dbeginner I can't reproduce the issue, you're gonna have to help me here if that's okay. Does `onDragGesture` gets called? That is, is `isDragging` true there? It should be because the offset isn't zero.

I'm just wondering why it doesn't get reset. Perhaps it's because of the block `withAnimation`. Could you check if this solves the problem?
```
.onReceive(NotificationCenter.default.publisher(for: UIScene.willDeactivateNotification), perform: { _ in
    if self.isDragging {
        #if !os(tvOS)
        self.draggingOffset = 0
        #endif
    }
})
```
```

**Comment by cocos2dbeginner** [comment]
@fermoya No problem, I got you. 
I made two videos (sorry, GIFs were too low res) to demonstrate the bug. I also logged the necessary variables/method calls.
Just tell me anytime when you need something. Willing to contribute :)
[SwiftUIPagerBugVideos_v2.zip](https://github.com/fermoya/SwiftUIPager/files/4886752/SwiftUIPagerBugVideos_v2.zip)

**Comment by fermoya** [comment]
@cocos2dbeginner thanks, the videos really helped! I noticed the `onChanged` was still getting called even if the App resigned being active. I've swapped notifications and I'm resetting the sate when becoming active again. Hopefully this solves it. See [v1.8.0-beta.3](https://github.com/fermoya/SwiftUIPager/releases/tag/1.8.0-beta.3)

**Comment by cocos2dbeginner** [comment]
@fermoya It solved it. Appreciate your effort :)

**Confirmation GIF**
![Uploading ezgif.com-video-to-gif (4).gif…]()
